---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to install java on ubuntu
    apt: 
      name: "{{myubuntujavapack}}"
      statess: present
    when: ansible_os_family =="Debian"
    ignore_errors: yes

  - name: i want to install java on redhat
    yum:
      name: "{{myredhatjavapack}}"
      state: present
    when: ansible_os_family =="RedHat"

