---
- hosts: all
  become: yes
  tasks:
  - name: i want to install wget on ubuntu
    apt:
      name: wget
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install wget on redhat
    yum:
      name: wget
      state: present
    when: ansible_os_family =="RedHat"
          